# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ffs_wrappers", use_symbols = TRUE, package_name = "ffs")

#' @usage NULL
#' @useDynLib ffs, .registration = TRUE
NULL

#' Returns a dataframe of file information for all files in the selected directory recursively
#' @export
dir_info <- function(path) .Call(wrap__dir_info, path)

#' Returns a dataframe of file information for all files in the selected directory recursively
#' @export
dir_info_par <- function(path) .Call(wrap__dir_info_par, path)


# nolint end
